# Generated by Django 3.1.3 on 2020-11-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet_paper_giveaway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
